apiVersion: v1
kind: Service
metadata:
  name: notes-api-service
  labels:
    app: notes-api
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: notes-api
